linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - goimports
    - gofmt

linters-settings:
  errcheck:
    exclude-functions:
      - (*json.Encoder).Encode
      - (*sql.Tx).Rollback
