services:
  nginx:
    container_name: nginx
    image: nginx:1.25
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: "app"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
    volumes:
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/my.cnf
      - ./volume/mysql:/var/lib/mysql
