services:
  nginx:
    container_name: nginx
    image: nginx:1.25
    volumes:
      - ./nginx/default-local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  frontend:
    container_name: frontend
    build:
      context: ./frontend
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/my.cnf
      - ./volume/mysql:/var/lib/mysql
  redoc:
    container_name: redoc
    image: redocly/redoc:v2.1.3
    ports:
      - 8081:80
    environment:
      SPEC_URL: "swagger/openapi.yaml"
    volumes:
      - ./docs:/usr/share/nginx/html/swagger/
